export * from './assistantPage/assistantPage.component';
export * from './audioToTextPage/audioToTextPage.component';
export * from './imageGenerationPage/imageGenerationPage.component';
export * from './imageTunningPage/imageTunningPage.component';
export * from './orthographyPage/orthographyPage.component';
export * from './prosConsPage/prosConsPage.component';
export * from './prosConsStreamPage/prosConsStreamPage.component';
export * from './textToAudioPage/textToAudioPage.component';
export * from './translatePage/translatePage.component';